/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/registry/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/search
     * @description Search person(s) in registry using identifier or custom attributes
     */
    post: operations['post_reg_search']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/on-search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/on-search
     * @description Search results through callback
     */
    post: operations['post_reg_on-search']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/subscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/subscribe
     * @description Subscribe to a life event with registry
     */
    post: operations['post_reg_subscribe']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/on-subscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/on-subscribe
     * @description Subscribe results through callback
     */
    post: operations['post_reg_on-subscribe']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/notify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/notify
     * @description Registry to notify a life event to subscrbiers
     */
    post: operations['post_reg_notify']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/unsubscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/unsubscribe
     * @description Unsubscribe existing subscription(s) by subscription_code
     */
    post: operations['post_reg_unsubscribe']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/on-unsubscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/on-unsubscribe
     * @description Unsubscribe response as a callback
     */
    post: operations['post_reg_on-unsubscribe']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/txn/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/txn/status
     * @description Perform async status check of previous civil registry transanctions using transaction_id and/or reference_id(s)
     */
    post: operations['post_reg_txnstatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/txn/on-status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/txn/on-status
     * @description Response to async status check of previous civil registrt transanctions using callback
     */
    post: operations['post_reg_on-txnstatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/sync/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/sync/search
     * @description Search person(s) in registry using identifier or custome attributes
     */
    post: operations['post_reg_sync_search']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/registry/sync/txn/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * /registry/sync/txn/status
     * @description Sync status check of registry Async APIs
     */
    post: operations['post_reg_sync_txnstatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Registry to notify a event to subscrbiers */
    NotifyEventRequest: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      notify_event: {
        reference_id: components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id']
        timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
        /** @description Registry data being notified as an outcome of event subscription with registry
         *      */
        data: {
          /** @default 1.0.0 */
          version: string
          reg_type?: components['schemas']['SearchResponse']['search_response']['items']['data']['reg_type']
          /**
           * @description @context: https://schema.spdci.org/common/v1/api-schemas/RegistryEventTypeEnum.jsonld <br>
           *     @type: "VitalEvent" <br>
           *
           *     **Notes:**
           *       1. Registry event type values defined as per implementation context.
           *       2. Usually a list of **enum** values of all possible queryable identifiers.
           *       3. example: "spdci-common:RegistryEventType:LiveBirth"
           *
           * @example spdci-common:RegistryEventType:LiveBirth
           */
          reg_event_type?: string
          reg_record_type: components['schemas']['SearchResponse']['search_response']['items']['data']['reg_record_type']
          /**
           * @description The "person" object contains fields expected in response of search
           *     @context: https://schema.spdci.org/extensions/crvs/v1/data/CRVSPerson.jsonld <br>
           *     @type: "Person" <br>
           *     @container: "@set" <br>
           *
           * @example {
           *       "type": "object",
           *       "description": "1. Attributes of a person to create fetch records, create verifiable credentials or use in search criteria.\n3. Allows Country/Registry specific implementation extensions using Attribute Name/Value pairs.\n\n@context: https://schema.spdci.org/extensions/crvs/v1/data/CRVSPerson.jsonld <br>\n@type: \"@context\" <br>\n",
           *       "example": {
           *         "@context": {
           *           "@vocab": "https://schema.spdci.org/core/v1",
           *           "xsd": "http://www.w3.org/2001/XMLSchema#",
           *           "schema": "http://schema.org/",
           *           "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
           *           "owl": "http://www.w3.org/2002/07/owl#"
           *         },
           *         "@id": "CRVS_Person_3",
           *         "@type": "CRVS_Person",
           *         "identifier": {
           *           "@id": "Identifier",
           *           "@type": "Identifier",
           *           "identifier_type": "UIN",
           *           "identifier_value": "197382465"
           *         },
           *         "name": {
           *           "@type": "Name",
           *           "surname": "Martinez",
           *           "given_name": "Elena",
           *           "second_name": "",
           *           "prefix": "Dr.",
           *           "suffix": "PhD"
           *         },
           *         "phone_number": [
           *           "+34612345678"
           *         ],
           *         "email": [
           *           "elena.martinez@example.com"
           *         ],
           *         "sex": "female",
           *         "birth_date": "1980-03-23T10:20:15",
           *         "birth_place": {
           *           "name": "hospital/Madrid_Central",
           *           "geo": {
           *             "@type": "GeoCoordinates",
           *             "latitude": 9.5604,
           *             "longitude": 100.0245
           *           },
           *           "address_line": "",
           *           "contained_in_place": "",
           *           "contains_place": [
           *             {
           *               "@id": "Place_3",
           *               "@type": "Place",
           *               "name": "Pattaya Floating Market",
           *               "address": "Bophut Koh Samui Surat Thani 84320 Thailand",
           *               "geo": {
           *                 "@type": "GeoCoordinates",
           *                 "latitude": 9.5617,
           *                 "longitude": 100.0259
           *               }
           *             }
           *           ]
           *         },
           *         "death_date": "",
           *         "death_place": "",
           *         "address": {
           *           "@id": "Address_1",
           *           "@type": "Address",
           *           "address_line1": "Bophut Koh Samui",
           *           "address_line2": "Surat, Near Big Buddha Beach",
           *           "locality": "Thani",
           *           "sub_region_code": "SH",
           *           "region_code": "A205",
           *           "postal_code": "84320",
           *           "country_code": "TH",
           *           "geo_location": {
           *             "@id": "GeoLocation_1",
           *             "@type": "GeoLocation",
           *             "plus_code": {
           *               "global_code": "8FW4V900+",
           *               "geometry": {
           *                 "@id": "geometry",
           *                 "@type": "GeoLocation",
           *                 "bounds": {
           *                   "@id": "bounds",
           *                   "@type": "geometry",
           *                   "northeast": {
           *                     "@id": "northeast",
           *                     "@type": "GeoCoordinates",
           *                     "latitude": 48.900000000000006,
           *                     "longitude": 2.4000000000000057
           *                   },
           *                   "southwest": {
           *                     "@id": "southwest",
           *                     "@type": "GeoCoordinates",
           *                     "latitude": 48.849999999999994,
           *                     "longitude": 2.3499999999999943
           *                   }
           *                 },
           *                 "location": {
           *                   "@id": "location",
           *                   "@type": "GeoCoordinates",
           *                   "latitude": 48.875,
           *                   "longitude": 2.375
           *                 }
           *               }
           *             }
           *           }
           *         },
           *         "marital_status": "S",
           *         "marriage_date": "",
           *         "divorce_date": "",
           *         "parent1_identifier": {
           *           "@id": "Identifier",
           *           "@type": "Identifier",
           *           "identifier_type": "UIN",
           *           "identifier_value": "537564821"
           *         },
           *         "parent2_identifier": {
           *           "@id": "Identifier",
           *           "@type": "Identifier",
           *           "identifier_type": "UIN",
           *           "identifier_value": "564582793"
           *         }
           *       }
           *     }
           */
          reg_records: Record<string, never>
        }
        locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
      }[]
    }
    /** @description 1. Functional registry specific extension to search.
     *     2. Additional checks using conditional expressions is possible.
     *     3. Allows Country/Registry specific implementation extensions using key/value pairs.
     *      */
    SearchRequest: {
      /**
       * @description 1. transaction_id set by txn initiating system (i.e sender) to co-relate all related requests in the context of a business transaction.
       *     2. transaction_id should be same across processing systems/service end points.
       *     2. transaction_id uniqueness is ensured by txn initiating system (i.e sender)
       *
       * @example XZFHYTY
       */
      transaction_id: string
      /** @description 1. Batch requests enable multiple individual requests with respective consent/authorize codes
       *      */
      search_request: {
        reference_id: components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id']
        timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
        search_criteria: {
          /** @default 1.0.0 */
          version: string
          reg_type?: components['schemas']['SearchResponse']['search_response']['items']['data']['reg_type']
          reg_record_type?: components['schemas']['SearchResponse']['search_response']['items']['data']['reg_record_type']
          /**
           * @description 1. Query format allow multiple ways to search registry
           *     2. Templatized query expressions with placeholder for conditional values
           *
           * @example expression
           * @enum {string}
           */
          query_type: 'idtype-value' | 'expression' | 'predicate' | 'graphql'
          /** @description 1. Implementing systems can define schemas.
           *     2. Based on context, pre defined named queries can also help as part of ExpTemplate construct.
           *     3. ExpressionWithConditionList is simple generic search query construct to solve for majority of search conditons. few examples: <br>
           *       - search or subscribe to update events; e.g any updates in postal_code 12345 between 1/jan/2020 and 31/dec/2020
           *       - search or subscribe to birth, death events; e.g any new birth in postal_code 12345 after 1/jan/2023
           *      */
          query:
            | {
                /**
                 * @description @context: https://schema.spdci.org/common/v1/api-schemas/QueryTypeEnum.jsonld <br>
                 *     @type: "QueryType" <br>
                 *
                 *     **Notes:**
                 *       1. Query types that helps decode query expressions
                 *       2. Sample query type enums: "graphql", "expression", "idtype-value"
                 *
                 * @example ns:org:QueryType:graphql
                 */
                type?: string
                /**
                 * @description @context: https://schema.spdci.org/common/v1/api-schemas/QueryExpression.jsonld <br>
                 *     @type: "QueryExpression" <br>
                 *
                 *     **Notes:**
                 *       1. Query expression's syntax / format is determined based on query-type.
                 *       2. Query expression as a template with placeholder to pass conditional search parameters
                 *
                 * @example {
                 *       "expression": "GeBirthRecordById {\n  person(UIN: \"1\") {\n    BRN\n    name\n    gender\n    birthDate\n    birthPlace\n    parents\n  }\n}\n"
                 *     }
                 */
                value?: Record<string, never>
              }
            | {
                /**
                 * @description @type: "IdType" <br>
                 *
                 *     **Notes:**
                 *       1. Identifier type values defined as per implementation context.
                 *       2. Usually a list of **enum** values of all possible queryable identifiers.
                 *       3. e.g: UIN, MOBILE, BRN, MRN, DRN, etc.,
                 *
                 * @example UIN
                 */
                type?: string
                /** @example 12314567890 */
                value?: unknown &
                  (string | number | boolean | Record<string, never>)
              }
            | {
                /**
                 * @description Sequence number to help define precedence for evaluating a list of expression Predicates
                 * @example 1
                 */
                seq_num?: number
                /** @description Expression */
                expression1: {
                  /**
                   * @description @context: https://schema.spdci.org/common/v1/api-schemas/QueryAttributes.jsonld <br>
                   *     @type: "QueryAttributes" <br>
                   *
                   *     **Notes:**
                   *       1. Query attribute names defined as per implementation context.
                   *       2. Usually a list of **enum** values of all possible queryable attribute names.
                   *       3. e.g: UIN, YOB, DOB, age, mobile, area-code, pin-code, etc.,
                   *
                   * @example YOB
                   */
                  attribute_name: string
                  /**
                   * @description Operator in an expression
                   * @example eq
                   * @enum {string}
                   */
                  operator: 'gt' | 'lt' | 'eq' | 'ge' | 'le' | 'in'
                  attribute_value: paths['/registry/search']['post']['requestBody']['content']['application/json']['schema']['message']['oneOf']['0']['search_request']['items']['search_criteria']['query']['anyOf']['1']['value']['allOf']['1']
                }
                /**
                 * @description Condition in an expression
                 * @example and
                 * @enum {string}
                 */
                condition?: 'and' | 'or' | 'not'
                expression2?: paths['/registry/search']['post']['requestBody']['content']['application/json']['schema']['message']['oneOf']['0']['search_request']['items']['search_criteria']['query']['anyOf']['2']['items']['expression1']
              }[]
          sort?: {
            /**
             * @description @type: "Attribute" <br>
             *
             *     **Notes:**
             *       1. Attribute names defined as per implementation context.
             *       2. Usually a list of **enum** values of all possible attribute names.
             *       3. e.g: UIN, poverty_score, etc.,
             *
             * @example poverty_score
             */
            attribute_name?: string
            /** @enum {string} */
            sort_order?: 'asc' | 'desc'
          }[]
          /** @description Pagination definition, count starts with 1 */
          pagination?: {
            /**
             * Format: int32
             * @example 2000
             */
            page_size: number
            /**
             * Format: int32
             * @default 1
             * @example 5
             */
            page_number: number
          }
          /**
           * @description @context: https://schema.spdci.org/common/v1/api-schemas/Consent.jsonld" <br>
           *     @type: "Consent"
           *
           * @example {
           *       "@context": "https://schema.spdci.org/common/v1/api-schemas/Consent.jsonld",
           *       "@type": "Consent",
           *       "ts": {
           *         "$ref": "#/components/schemas/MsgHeader_V1.0.0/properties/message_ts"
           *       },
           *       "purpose": {
           *         "text": {
           *           "type": "string"
           *         },
           *         "code": {
           *           "type": "string",
           *           "description": "From a fixed set, documented at refUri"
           *         },
           *         "ref_uri": {
           *           "type": "string",
           *           "format": "uri",
           *           "description": "Uri to provide more info on consent codes"
           *         }
           *       }
           *     }
           */
          consent?: Record<string, never>
          /**
           * @description @context: https://schema.spdci.org/common/v1/api-schemas/Authorize.jsonld <br>
           *     @type: "Authorize"
           *
           * @example {
           *       "@context": "https://schema.spdci.org/common/v1/api-schemas/Authorize.jsonld",
           *       "@type": "Authorize",
           *       "ts": {
           *         "$ref": "#/components/schemas/MsgHeader_V1.0.0/properties/message_ts"
           *       },
           *       "purpose": {
           *         "text": {
           *           "type": "string"
           *         },
           *         "code": {
           *           "type": "string",
           *           "description": "From a fixed set, documented at refUri"
           *         },
           *         "ref_uri": {
           *           "type": "string",
           *           "format": "uri",
           *           "description": "Uri to provide more info on authorize codes"
           *         }
           *       }
           *     }
           */
          authorize?: Record<string, never>
        }
        locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
      }[]
    }
    /** @description Response to search request. Multiple repsonses for each page can be pushed to the caller as an implementation! */
    SearchResponse: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      /**
       * @description 1. correlation_id acknowledged by end txn processing system (i.e receiver) to co-relate all related requests in the context of a business transaction.
       *     2. correlation_id uniqueness is ensured by txn processing system (i.e receiver)
       *
       * @example ABC9876543210
       */
      correlation_id: string
      search_response: {
        reference_id: components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id']
        timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
        status: components['schemas']['UnSubscribeResponse']['status']
        status_reason_code?: components['schemas']['SearchStatusReasonCode']
        /** @description Status reason code message. Helps actionanble messaging for systems/end users */
        status_reason_message?: string
        /** @description Search result record as an outcome of search/subscribe action
         *      */
        data?: {
          /** @default 1.0.0 */
          version: string
          /**
           * @description @context:https://schema.spdci.org/common/v1/api-schemas/RegistryType.jsonld <br>
           *     @type: "@context" <br>
           *
           *     **Notes:**
           *       1. Registry type values defined as per implementation context.
           *       2. Usually a list of **enum** values of all possible queryable functional registries
           *       3. example: "ns:org:RegistryType:Civil"
           *
           * @example ns:org:RegistryType:Civil
           */
          reg_type?: string
          /**
           * @description @context: https://schema.spdci.org/common/v1/api-schemas/RegistryRecordType.jsonld <br>
           *     @type: "RegistryRecordType" <br>
           *
           *     **Notes:**
           *       1. Registry record type values defined as per implementation context.
           *       2. Usually a list of **enum** values of all possible queryable result sets
           *       3. Referenced in search_request and notify events
           *       4. example: "spdci-extensions-dci:Person"
           *
           * @example spdci-extensions-dci:Person
           */
          reg_record_type?: string
          /** @description The "Entity" object contains fields expected in response of search
           *     @context: https://schema.spdci.org/extensions/crvs/v1/data/CRVSPerson.jsonld <br>
           *     @type: "Person" <br>
           *     @container: "@set" <br>
           *      */
          reg_records: Record<string, never>[]
        }
        /** @description Pagination definition, count starts with 1 */
        pagination?: {
          /**
           * Format: int32
           * @example 2000
           */
          page_size: number
          /**
           * Format: int32
           * @example 5
           */
          page_number: number
          /**
           * Format: int32
           * @example 24250
           */
          total_count: number
        }
        locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
      }[]
    }
    /**
     * @description Identity verification request status reason codes
     * @enum {string}
     */
    SearchStatusReasonCode:
      | 'rjct.reference_id.invalid'
      | 'rjct.reference_id.duplicate'
      | 'rjct.timestamp.invalid'
      | 'rjct.search_criteria.invalid'
      | 'rjct.filter.invalid'
      | 'rjct.sort.invalid'
      | 'rjct.pagination.invalid'
      | 'rjct.search.too_many_records_found'
    /** @description Subscribe to a life event with crvs */
    SubscribeRequest: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      subscribe_request: {
        reference_id: components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id']
        timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
        subscribe_criteria: {
          /** @default 1.0.0 */
          version: string
          /**
           * @description @context:https://schema.spdci.org/common/v1/api-schemas/RegistryType.jsonld <br>
           *     @type: "@context" <br>
           *
           *     **Notes:**
           *       1. Registry type values defined as per implementation context.
           *       2. Usually a list of **enum** values of all possible queryable functional registries
           *       3. example: "ns:org:RegistryType:Social"
           *
           * @example ns:org:RegistryType:Social
           */
          reg_type?: string
          /**
           * @description @context: https://schema.spdci.org/common/v1/api-schemas/RegistryEventTypeEnum.jsonld <br>
           *     @type: "VitalEvent" <br>
           *
           *     **Notes:**
           *       1. Registry event type values defined as per implementation context.
           *       2. Usually a list of **enum** values of all possible queryable identifiers.
           *       3. example: "spdci-common:RegistryEventType:LiveBirth"
           *
           * @example spdci-common:RegistryEventType:LiveBirth
           */
          reg_event_type: string
          /** @description 1. Frequency at which subscribed services should be notified.
           *     2. start_time, end_time represent data range where the notification frequency is applicable
           *      */
          frequency?: {
            start_time: components['schemas']['MsgHeader_V1.0.0']['message_ts']
            end_time: components['schemas']['MsgHeader_V1.0.0']['message_ts']
            /** @description Frequency at which notification is required. This will be in the form of cron expression.
             *     Example - "0 0 0 5,15 * ? *"
             *     which says At 00:00:00am, on the 5th and 15th day, every month
             *      */
            frequency: string
          }
          filter_type?: components['schemas']['SearchRequest']['search_request']['items']['search_criteria']['query_type']
          /** @description 1. Implementing systems can define schemas.
           *     2. Based on context, pre defined named queries can also help as part of ExpTemplate construct.
           *     3. ExpressionWithConditionList is simple generic search query construct to solve for majority of search conditons. few examples: <br>
           *       - search or subscribe to update events; e.g any updates in postal_code 12345 between 1/jan/2020 and 31/dec/2020
           *       - search or subscribe to birth, death events; e.g any new birth in postal_code 12345 after 1/jan/2023
           *      */
          filter:
            | {
                /**
                 * @description @context: https://schema.spdci.org/common/v1/api-schemas/QueryTypeEnum.jsonld <br>
                 *     @type: "QueryType" <br>
                 *
                 *     **Notes:**
                 *       1. Query types that helps decode query expressions
                 *       2. Sample query type enums: "graphql", "expression", "idtype-value"
                 *
                 * @example ns:org:QueryType:graphql
                 */
                type?: string
                /**
                 * @description @context: https://schema.spdci.org/common/v1/api-schemas/QueryExpression.jsonld <br>
                 *     @type: "QueryExpression" <br>
                 *
                 *     **Notes:**
                 *       1. Query expression's syntax / format is determined based on query-type.
                 *       2. Query expression as a template with placeholder to pass conditional search parameters
                 *
                 * @example {
                 *       "expression": "query GetMemberByIdentifier {\n  member(\n    identifier: {\n      value: \"1\",\n      type: \"uin\"\n    }\n  ) {\n    member_identifier {\n      value\n      type\n    }\n    demographic_info {\n      name\n      gender\n      age\n    }\n  }\n}\n"
                 *     }
                 */
                value?: Record<string, never>
              }
            | paths['/registry/search']['post']['requestBody']['content']['application/json']['schema']['message']['oneOf']['0']['search_request']['items']['search_criteria']['query']['anyOf']['1']
            | paths['/registry/search']['post']['requestBody']['content']['application/json']['schema']['message']['oneOf']['0']['search_request']['items']['search_criteria']['query']['anyOf']['2']
          /**
           * @description @context: https://schema.spdci.org/common/v1/api-schemas/RegistryRecordType.jsonld <br>
           *     @type: "RegistryRecordType" <br>
           *
           *     **Notes:**
           *       1. Registry record type values defined as per implementation context.
           *       2. Usually a list of **enum** values of all possible queryable result sets
           *       3. Referenced in search_request and notify events
           *       4. example: "spdci-extensions-dci:Member"
           *
           * @example spdci-extensions-dci:Member
           */
          notify_record_type: string
          authorize?: components['schemas']['SearchRequest']['search_request']['items']['search_criteria']['authorize']
        }
        locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
      }[]
    }
    /** @description Response to subscribe request. */
    SubscribeResponse: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      correlation_id: components['schemas']['SearchResponse']['correlation_id']
      subscribe_response: {
        reference_id: components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id']
        timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
        status: components['schemas']['UnSubscribeResponse']['status']
        status_reason_code?: components['schemas']['SubscribeStatusReasonCode']
        /** @description Status reason code message. Helps actionable messaging for systems/end users */
        status_reason_message?: string
        subscriptions?: {
          /** @default 1.0.0 */
          version: string
          code: components['schemas']['UnSubscribeRequest']['subscription_codes']['items']
          status: components['schemas']['UnSubscribeResponse']['subscription_status']['items']['status']
          timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
          reg_type?: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['reg_type']
          reg_event_type?: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['reg_event_type']
          frequency?: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['frequency']
          filter_type?: components['schemas']['SearchRequest']['search_request']['items']['search_criteria']['query_type']
          filter?: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['filter']
          notify_record_type?: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['notify_record_type']
          locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
        }[]
        pagination?: components['schemas']['SearchResponse']['search_response']['items']['pagination']
        locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
      }[]
    }
    /**
     * @description Identity verification request status reason codes
     * @enum {string}
     */
    SubscribeStatusReasonCode:
      | 'rjct.reference_id.invalid'
      | 'rjct.reference_id.duplicate'
      | 'rjct.timestamp.invalid'
      | 'rjct.notify_types.invalid'
      | 'rjct.notify_details.invalid'
      | 'rjct.person_id.invalid'
      | 'rjct.event.already_subscribed'
    /** @description Request to fetch txn status on various service requests */
    TxnStatusRequest: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      txnstatus_request: {
        /**
         * @description Unique reference_id set by txn initiating system for each request in a batch
         * @example SDFRTYUX
         */
        reference_id: string
        /**
         * @description txn type to fetch status
         * @enum {string}
         */
        txn_type: 'search' | 'subscribe' | 'unsubscribe'
        /** @enum {string} */
        attribute_type:
          | 'transaction_id'
          | 'reference_id_list'
          | 'correlation_id'
          | 'subscription_code_list'
        attribute_value:
          | components['schemas']['SearchRequest']['transaction_id']
          | components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id'][]
          | components['schemas']['SearchResponse']['correlation_id']
          | unknown
        /**
         * @description indicates language code. SPDCI Connect supports country codes as per ISO 639.3 standard
         * @example eng
         */
        locale?: string
      }
    }
    /** @description txn status info on various service requests */
    TxnStatusResponse: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      correlation_id: components['schemas']['SearchResponse']['correlation_id']
      txnstatus_response: {
        /**
         * @description txn type to fetch status
         * @enum {string}
         */
        txn_type?: 'search' | 'subscribe' | 'unsubscribe'
        txn_status?:
          | {
              transaction_id: components['schemas']['SearchRequest']['transaction_id']
              correlation_id: components['schemas']['SearchResponse']['correlation_id']
              search_response: {
                reference_id: components['schemas']['TxnStatusRequest']['txnstatus_request']['reference_id']
                timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
                status: components['schemas']['UnSubscribeResponse']['status']
                status_reason_code?: components['schemas']['SearchStatusReasonCode']
                /** @description Status reason code message. Helps actionanble messaging for systems/end users */
                status_reason_message?: string
                /** @description Search result record as an outcome of search/subscribe action
                 *      */
                data?: {
                  /** @default 1.0.0 */
                  version: string
                  reg_type?: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['reg_type']
                  reg_record_type: components['schemas']['SubscribeRequest']['subscribe_request']['items']['subscribe_criteria']['notify_record_type']
                  /**
                   * @description The "person" object contains fields expected in response of search
                   *     @context: https://schema.spdci.org/core/v1/data/Member.jsonld <br>
                   *     @type: "Person" <br>
                   *     @container: "@set" <br>
                   *
                   * @example {
                   *       "type": "object",
                   *       "description": "1. Attributes of a person to create fetch records, create verifiable credentials or use in search criteria.\n3. Allows Country/Registry specific implementation extensions using Attribute Name/Value pairs.\n\n@context: https://schema.spdci.org/core/v1/data/Member.jsonld <br>\n@type: \"@context\" <br>\n",
                   *       "example": {
                   *         "@context": {
                   *           "spdci": "https://schema.spdci.org/core/v1/data",
                   *           "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                   *           "xsd": "http://www.w3.org/2001/XMLSchema#",
                   *           "owl": "http://www.w3.org/2002/07/owl#",
                   *           "common": "https://schema.spdci.org/common/v1/"
                   *         },
                   *         "@id": "https://example.org/sr_person/847951632",
                   *         "@type": "spdci:member",
                   *         "member_identifier": [
                   *           {
                   *             "@type": "Identifier",
                   *             "identifier_type": "UIN",
                   *             "identifier_value": "42343545654"
                   *           }
                   *         ],
                   *         "demographic_info": {
                   *           "@type": "SRPerson",
                   *           "identifier": [
                   *             {
                   *               "@type": "Identifier",
                   *               "identifier_type": "NationalID",
                   *               "identifier_value": "9876543210"
                   *             }
                   *           ],
                   *           "name": {
                   *             "@type": "Name",
                   *             "surname": "Smith",
                   *             "given_name": "Alice",
                   *             "prefix": "Ms.",
                   *             "suffix": ""
                   *           },
                   *           "sex": "female",
                   *           "birth_date": "1985-05-20"
                   *         },
                   *         "related_person": [
                   *           {
                   *             "@type": "RelatedPerson",
                   *             "relationship_type": "spouse",
                   *             "related_member": {
                   *               "@type": "Member",
                   *               "@id": "https://example.org/member/123456789",
                   *               "member_identifier": "M123456789"
                   *             }
                   *           },
                   *           {
                   *             "@type": "RelatedPerson",
                   *             "relationship_type": "child",
                   *             "related_member": {
                   *               "@type": "Member",
                   *               "@id": "https://example.org/member/987654322",
                   *               "spdci:member_identifier": "M987654322"
                   *             }
                   *           }
                   *         ],
                   *         "is_disabled": false,
                   *         "marital_status": "married",
                   *         "employment_status": "employed",
                   *         "occupation": "teacher",
                   *         "income_level": "middle",
                   *         "language_code": [
                   *           "en",
                   *           "es"
                   *         ],
                   *         "education_level": "bachelor",
                   *         "additional_attributes": [
                   *           {
                   *             "extra_work": "volunteer"
                   *           }
                   *         ],
                   *         "registration_date": "2022-01-10T08:00:00Z",
                   *         "last_updated": "2023-06-15T10:00:00Z"
                   *       }
                   *     }
                   */
                  reg_records: Record<string, never>
                }
                pagination?: components['schemas']['SearchResponse']['search_response']['items']['pagination']
                locale?: components['schemas']['TxnStatusRequest']['txnstatus_request']['locale']
              }[]
            }
          | components['schemas']['SubscribeResponse']
          | components['schemas']['UnSubscribeResponse']
      }
    }
    /** @description Un-Subscribe to registred subscriptions */
    UnSubscribeRequest: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
      subscription_codes: string[]
    }
    /** @description Un-Subscribe to a life event with crvs */
    UnSubscribeResponse: {
      transaction_id: components['schemas']['SearchRequest']['transaction_id']
      correlation_id: components['schemas']['SearchResponse']['correlation_id']
      timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
      /**
       * @description Request (e.g disburse, link, unlink, resolve, issue, search, verify, etc.,) status: <br> 1. rcvd: Received; Request received <br> 2. pdng: Pending; Request initiated <br> 3. succ: Success; Request successful <br> 4. rjct: Rejected; Request rejected
       * @enum {string}
       */
      status: 'rcvd' | 'pdng' | 'succ' | 'rjct'
      status_reason_code?: components['schemas']['UnSubscribeStatusReasonCode']
      /** @description Status reason code message. Helps actionanble messaging for systems/end users */
      status_reason_message?: string
      subscription_status?: {
        code: components['schemas']['UnSubscribeRequest']['subscription_codes']['items']
        /**
         * @description subscription status
         * @enum {string}
         */
        status: 'subscribe' | 'unsubscribe'
      }[]
    }
    /**
     * @description Identity verification request status reason codes
     * @enum {string}
     */
    UnSubscribeStatusReasonCode:
      | 'rjct.reference_id.invalid'
      | 'rjct.reference_id.duplicate'
      | 'rjct.timestamp.invalid'
      | 'rjct.subscription_code.invalid'
      | 'rjct.requester.invalid'
      | 'rjct.event.already_unsubscribed'
    /** @description Encrypted payload */
    EncryptedMessage: {
      header: {
        /** @description The JWE algorithm used for encryption */
        alg: string
        /** @description The encryption algorithm used for encrypting the plaintext */
        enc: string
        /** @description The key identifier for the encryption key */
        kid: string
      }
      /** @description This is the result of encrypting the plaintext using the CEK and the IV. It's Base64Url-encoded. */
      ciphertext: string
      /** @description The base64-url encoded encrypted key */
      encrypted_key: string
      /** @description This is a Base64Url-encoded value that provides evidence of the integrity and authenticity of the ciphertext, Initialization Vector, and Additional Authenticated Data */
      tag: string
      /** @description This is a Base64Url-encoded random bit string to be used as the Initialization Vector (IV) when encrypting the plaintext to produce the ciphertext. The size of the IV depends on the encryption algorithm used. */
      iv: string
    }
    /** @description Commumication layer Asyn errors that are returned as part of message acknowledgement.
     *     1. Messages that are not parsable or message integrity check fails.
     *     2. This object may be used across all transport layer protocols (https, sftp, messaging, etc,) to ack the receipt of a message.
     *     3. Business context and related validation is NOT in scope of this error object.
     *      */
    Error: {
      /**
       * @description Standard error code
       * @enum {string}
       */
      code?:
        | 'err.request.bad'
        | 'err.request.unauthorized'
        | 'err.request.forbidden'
        | 'err.request.not_found'
        | 'err.request.timeout'
        | 'err.version.not_supported'
        | 'err.request.too_many_requests'
        | 'err.sender_id.invalid'
        | 'err.sender_uri.invalid'
        | 'err.receiver_id.invalid'
        | 'err.signature.missing'
        | 'err.signature.invalid'
        | 'err.encryption.invalid'
        | 'err.service.unavailable'
      /** @description message to describe above error code */
      message?: string
    }
    /** @description File info. Used in file upload feature using HTTPS */
    FileInfo: {
      /** @description SPDCI Connect specific actions. Usually verb from the URI should go here to help store and fwd kind of processing requirements. */
      action: string
      /**
       * Format: binary
       * @description Disbursement instruction file representing Disburse or OnDisburse end point elements i.e signature/header/message entities as a file record
       */
      fileName: string
      /**
       * @description File content format. e.g json, csv, etc.,
       * @default json
       * @example csv
       */
      fileFormat: string
    }
    /** @description Message header */
    'MsgCallbackHeader_V1.0.0': {
      /**
       * @description Messaing protocol specification version being used
       * @default 1.0.0
       */
      version: string
      /**
       * @description 1. Unique message id to communicate between sender and receiver systems to realiable deliver the message over any transport layer i.e https, pub/sub, sftp etc.,
       *     2. The scope of message_id end with successful ack of the message by the receiver.
       *     3. To realy the message between hops, underlying relying parties may consider to store and forward the message with integirty, ie Signature intact.
       *
       * @example 789
       */
      message_id: string
      message_ts: components['schemas']['MsgHeader_V1.0.0']['message_ts']
      /** @description SPDCI Connect specific action. Usually verb from the URI should go here to help store and fwd kind of processing requirements. */
      action: string
      status: components['schemas']['UnSubscribeResponse']['status']
      /**
       * @description Message header related common status reason codes
       * @enum {string}
       */
      status_reason_code?:
        | 'rjct.version.invalid'
        | 'rjct.message_id.duplicate'
        | 'rjct.message_ts.invalid'
        | 'rjct.action.invalid'
        | 'rjct.action.not_supported'
        | 'rjct.total_count.invalid'
        | 'rjct.total_count.limit_exceeded'
        | 'rjct.errors.too_many'
      /** @description Status reascon code message, if any, Helps actionable messaging for system/end users */
      status_reason_message?: string
      /**
       * @description Total no of requests present in the message request
       * @example 21800
       */
      total_count?: number
      /**
       * @description No of requests in complteed state. Complete includes success and error requests due to funcational errors
       * @example 50
       */
      completed_count?: number
      /**
       * @description 1. sender_id registered with the receiving system or gateway.
       *     2. Used for authorization, encryption, digital sign verfication, etc.,
       *
       * @example civilregistry.example.org
       */
      sender_id?: string
      /**
       * @description receiver id registered with the calling system. Used for authorization, encryption, digital sign verfication, etc., functions.
       * @example registry.example.org
       */
      receiver_id?: string
      /**
       * @description Is message encrypted?
       * @default false
       */
      is_msg_encrypted: boolean
      meta?: components['schemas']['MsgHeader_V1.0.0']['meta']
    }
    /** @description Message header */
    'MsgHeader_V1.0.0': {
      /**
       * @description Messaing protocol specification version being used
       * @default 1.0.0
       */
      version: string
      /**
       * @description 1. Unique message id to communicate between sender and receiver systems to realiable deliver the message over any transport layer i.e https, pub/sub, sftp etc.,
       *     2. The scope of message_id end with successful ack of the message by the receiver.
       *     3. To realy the message between hops, underlying relying parties may consider to store and forward the message with integirty, ie Signature intact.
       *
       * @example 123
       */
      message_id: string
      /**
       * Format: date-time
       * @description 1. All dates and timestamps are represented in [ISO 8601](https://www.iso.org/standard/40874.html) format including timezone - e.g 2022-12-04T17:20:07-04:00.
       *
       * @example 2022-12-04T17:20:07-04:00
       */
      message_ts: string
      /** @description spdci Connect specific action. Usually verb from the URI. Helps in sync, async, store/fwd processing. Helps to identify payload type in message property. */
      action: string
      /**
       * @description 1. sender_id registered with the receiving system or gateway.
       *     2. Used for authorization, encryption, digital sign verification, etc.,
       *
       * @example spp.example.org
       */
      sender_id: string
      /**
       * Format: uri
       * @description 1. sender url to accept callbacks. Applicable only for async communications and if response ack_status is ACK.
       *     2. Default uri is assumed to be configured on the gateway as part of sender/receiver onboarding.
       *     3. For SFTP based communications, this shall be set to server/folder details.
       *
       * @example https://spp.example.org/consumer-space/callback/on-search
       */
      sender_uri?: string
      /**
       * @description receiver id registered with the calling system. Used for authorization, encryption, digital sign verification, etc., functions.
       * @example civilregistry.example.org
       */
      receiver_id?: string
      /**
       * @description Total no of requests present in the message request
       * @example 21800
       */
      total_count: number
      /**
       * @description Is message encrypted?
       * @default false
       */
      is_msg_encrypted: boolean
      /** @description @context: https://schema.spdci.org/common/v1/api-schemas/Meta.jsonld <br>
       *     @type: "@context" <br>
       *
       *     **Notes:**
       *       1. Additional meta info defined as per implementation context.
       *       2. Usually unencrypted list of name/value, tags, etc., to provide additional info to intermediary entities.
       *       3. The information SHOULD be privacy preserving
       *      */
      meta?: Record<string, never>
    }
    /**
     * @description Signature of {header}+{message} body verified using sender's signing public key
     * @example Signature:  namespace="spdci", kidId="{sender_id}|{unique_key_id}|{algorithm}", algorithm="ed25519", created="1606970629", expires="1607030629", headers="(created) (expires) digest", signature="Base64(signing content)
     */
    MsgSignature: string
  }
  responses: {
    /** @description Acknowledgement of message received after successful validation of message and signature */
    Response: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          message?: {
            /**
             * @description 1. ACK: If the request is valid (for basic checks) and async callback (i.e webhook) will be invoked by reciever back to the sender.
             *     2. NACK: If the request is valid (for basic checks) and there is no futher updates from reciever back to the sender.
             *     3. ERR: If the reuqest is invalid and reciver can't process the request. error object holds error code, message.
             *
             * @enum {string}
             */
            ack_status: 'ACK' | 'NACK' | 'ERR'
            timestamp: components['schemas']['MsgHeader_V1.0.0']['message_ts']
            error?: components['schemas']['Error']
            correlation_id: components['schemas']['SearchResponse']['correlation_id']
          }
        }
      }
    }
    /** @description HTTP layer error details */
    HttpErrorResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          errors?: unknown
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  post_reg_search: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'search'
          }
          /** @description The search data using which registry search to be performed */
          message:
            | components['schemas']['SearchRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'search'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  'post_reg_on-search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'on-search'
          }
          message?:
            | components['schemas']['SearchResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'on-search'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  post_reg_subscribe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'subscribe'
          }
          /** @description Subscription request which contaion query with frequency and other info on which notification to be sent by registry to subscriber */
          message:
            | components['schemas']['SubscribeRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'subscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  'post_reg_on-subscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'on-subscribe'
          }
          /** @description Subscription information */
          message:
            | components['schemas']['SubscribeResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'on-subscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  post_reg_notify: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'notify'
          }
          message?:
            | components['schemas']['NotifyEventRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'notify'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  post_reg_unsubscribe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'unsubscribe'
          }
          /** @description The unsubscribe request that contain subscription ids which to be removed from subscription list */
          message:
            | components['schemas']['UnSubscribeRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'unsubscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  'post_reg_on-unsubscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'on-unsubscribe'
          }
          message:
            | components['schemas']['UnSubscribeResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'on-unsubscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  post_reg_txnstatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'txn-status'
          }
          message:
            | components['schemas']['TxnStatusRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'txn-status'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  'post_reg_on-txnstatus': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'txn-on-status'
          }
          message?:
            | components['schemas']['TxnStatusResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'txn-on-status'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  post_reg_sync_search: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'search'
          }
          /** @description The search data using which registry search to be performed */
          message:
            | components['schemas']['SearchRequest']
            | components['schemas']['EncryptedMessage']
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      /** @description Registry search response */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            signature?: components['schemas']['MsgSignature']
            header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
              /** @enum {unknown} */
              action?: 'on-search'
            }
            message?:
              | components['schemas']['SearchResponse']
              | components['schemas']['EncryptedMessage']
          }
        }
      }
    }
  }
  post_reg_sync_txnstatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'txn-status'
          }
          message:
            | components['schemas']['TxnStatusRequest']
            | components['schemas']['EncryptedMessage']
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      /** @description Transaction status check response */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            signature?: components['schemas']['MsgSignature']
            header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
              /** @enum {unknown} */
              action?: 'txn-on-status'
            }
            message?:
              | components['schemas']['TxnStatusResponse']
              | components['schemas']['EncryptedMessage']
          }
        }
      }
    }
  }
}
