/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/registry/search': {
    /**
     * /registry/search
     * @description Search person(s) in registry using identifier or custome attributes
     */
    post: operations['post_reg_search']
  }
  '/registry/on-search': {
    /**
     * /registry/on-search
     * @description Search results through callback
     */
    post: operations['post_reg_on-search']
  }
  '/registry/subscribe': {
    /**
     * /registry/subscribe
     * @description Subscribe to a life event with registry
     */
    post: operations['post_reg_subscribe']
  }
  '/registry/on-subscribe': {
    /**
     * /registry/on-subscribe
     * @description Subscribe results through callback
     */
    post: operations['post_reg_on-subscribe']
  }
  '/registry/notify': {
    /**
     * /registry/notify
     * @description Registry to notify a life event to subscrbiers
     */
    post: operations['post_reg_notify']
  }
  '/registry/unsubscribe': {
    /**
     * /registry/unsubscribe
     * @description Unsubscribe existing subscription(s) by subscription_code
     */
    post: operations['post_reg_unsubscribe']
  }
  '/registry/on-unsubscribe': {
    /**
     * /registry/on-unsubscribe
     * @description Unsubscribe response as a callback
     */
    post: operations['post_reg_on-unsubscribe']
  }
  '/registry/txn/status': {
    /**
     * /registry/txn/status
     * @description Perform async status check of previous civil registry transanctions using transaction_id and/or reference_id(s)
     */
    post: operations['post_reg_txnstatus']
  }
  '/registry/txn/on-status': {
    /**
     * /registry/txn/on-status
     * @description Response to async status check of previous civil registrt transanctions using callback
     */
    post: operations['post_reg_on-txnstatus']
  }
  '/registry/sync/search': {
    /**
     * /registry/sync/search
     * @description Search person(s) in registry using identifier or custome attributes
     */
    post: operations['post_reg_sync_search']
  }
  '/registry/sync/txn/status': {
    /**
     * /registry/sync/txn/status
     * @description Sync status check of registry Async APIs
     */
    post: operations['post_reg_sync_txnstatus']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /**
     * Format: ^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+$
     * @description 1. Person id is case insensitve normative represenation as id-type:id@provider <br>
     * 2. This will enumerate foundational and functioanl id's to easily resolvable addressess <br>
     * 3. This property is intended to unambiguously refer to an object, such as a person, beneficiary, user, etc., <br>
     * 4. Few examples: <br>
     *     - id@identifier-type.id-provider e.g token:12345@nid, vid:543215@nid <br>
     *     - id@civil-registry.issuing-agency e.g id:12345@civil-reg, brn:12345@civil-reg, mrn:12345@civil-reg <br>
     *     - id@functional-identifier.issuing-agency e.g id:12345@voter-id, id:12345@driving-license, mobile:12345@farmer-reg <br>
     * Note: id provider should be made configurable and solutions should adapt to the local jurisdiction and policies.
     *
     * @example vid:54321@nid
     */
    cdpi_PersonId: string
    /**
     * @description @context: "https://example.org/schema/CRVSPerson" <br>
     * @type: "Consent"
     *
     * @example {
     *   "@context": "https://example.org/schema/CRVSPerson",
     *   "@type": "CRVSPerson",
     *   "@vocab": "https://spdci.org/",
     *   "schema": "http://schema.org/",
     *   "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
     *   "xsd": "http://www.w3.org/2001/XMLSchema#",
     *   "CRVSPerson": {
     *     "@id": "https://spdci.org/CRVSPerson",
     *     "@type": "rdfs:Class",
     *     "@context": {
     *       "name": {
     *         "@id": "schema:name",
     *         "@type": "xsd:string"
     *       },
     *       "givenName": {
     *         "@id": "schema:givenName",
     *         "@type": "xsd:string"
     *       },
     *       "familyName": {
     *         "@id": "schema:familyName",
     *         "@type": "xsd:string"
     *       },
     *       "additionalName": {
     *         "@id": "schema:additionalName",
     *         "@type": "xsd:string"
     *       },
     *       "gender": {
     *         "@id": "schema:gender",
     *         "@type": "xsd:string"
     *       },
     *       "birthDate": {
     *         "@id": "schema:birthDate",
     *         "@type": "xsd:date"
     *       },
     *       "birthPlace": {
     *         "@id": "schema:birthPlace",
     *         "@type": "schema:GeoCoordinates"
     *       },
     *       "deathDate": {
     *         "@id": "schema:deathDate",
     *         "@type": "xsd:date"
     *       },
     *       "deathPlace": {
     *         "@id": "schema:deathPlace",
     *         "@type": "schema:GeoCoordinates"
     *       },
     *       "maritalStatus": {
     *         "@id": "schema:maritalStatus",
     *         "@type": "xsd:string"
     *       },
     *       "honorificPrefix": {
     *         "@id": "schema:honorificPrefix",
     *         "@type": "xsd:string"
     *       },
     *       "honorificSuffix": {
     *         "@id": "schema:honorificSuffix",
     *         "@type": "xsd:string"
     *       },
     *       "emails": {
     *         "@container": "@set",
     *         "@id": "schema:email",
     *         "@type": "xsd:string"
     *       },
     *       "telephones": {
     *         "@container": "@set",
     *         "@id": "schema:telephone",
     *         "@type": "xsd:string"
     *       },
     *       "address": {
     *         "@id": "schema:address",
     *         "@type": "schema:GeoCoordinates"
     *       },
     *       "marriageDate": {
     *         "@id": "https://spdci.org/marriageDate",
     *         "@type": "xsd:date"
     *       },
     *       "divorceDate": {
     *         "@id": "https://spdci.org/divorceDate",
     *         "@type": "xsd:date"
     *       },
     *       "parents": {
     *         "@id": "schema:parents",
     *         "@type": "https://spdci.org/CRVSPerson"
     *       }
     *     }
     *   },
     *   "@id": "https://spdci.org/CRVSPerson"
     * }
     */
    dci_CRVSPerson: Record<string, never>
    /**
     * @description An identifier type includes unique numbers legally assigned to individuals. <br>
     * Reference: [Types of ID](https://id4d.worldbank.org/guide/types-id-systems)
     *
     * UIN : Unique Identification Number <br>
     * BRN : Birth Registration Number or Birth Serial Number <br>
     * MRN : Marriage Registration Number <br>
     * DRN : Death Registration Number <br>
     *
     * @enum {string}
     */
    dci_IdentifierType: 'UIN' | 'BRN' | 'MRN' | 'DRN'
    dci_IdentifierTypeValue: {
      identifier_type?: components['schemas']['dci_IdentifierType']
      /** @description Value of the identifier */
      identifier_value?: string
    }
    /**
     * @description Marital status reference database: Standardized codes/values representing different marital status categories <br>
     * Reference: [FHIR Marital Status](https://hl7.org/fhir/DSTU2/valueset-marital-status.html)<br>
     *
     * Code : Values - Description <br>
     * S : Never Married - No marriage contract has ever been entered <br>
     * M : Married - A current marriage contract is active <br>
     * W : Widow - The spouse has died <br>
     * A : Annulled - Marriage contract has been declared null and to not have existed <br>
     * D : Divorced - Marriage contract has been declared dissolved and inactive <br>
     * L : Legally Separated - Legally Separated <br>
     * U : Unmarried - The person is not presently married. The marital history is not known or stated. <br>
     *
     * @enum {string}
     */
    dci_MaritalStatus: 'S' | 'M' | 'W' | 'A' | 'D' | 'L' | 'U'
    /**
     * @description The name data object represents a person's name with various components. <br>
     * Reference: [FHIR XPN - extended person name](https://v2plus.hl7.org/2021Jan/data-type/XPN.html#XPN-1) <br>
     * Note: Note: In some cultures, people can have multiple Surname(s), Given name(s), Second name(s), Suffix(s), or Prefix(s) to their name; all can be present in the respective attributes, being separated by separator character like space or /.
     */
    dci_Name: {
      /** @description Surname(s) or last name(s) of the applicant */
      sur_name?: string
      /** @description Given name(s) or first name(s) of the applicant */
      given_name?: string
      /** @description Second name(s) or middle name(s) of the applicant */
      second_name?: string
      /** @description Suffix part of the applicant's name */
      suffix?: string
      /** @description Prefix part of the applicant's name */
      prefix?: string
    }
    /**
     * @description 1. Attributes of a person to create fetch records, create verifiable credentials or use in search criteria.
     * 3. Allowes Country/Registry specific implementation extensions using Attribute Name/Value pairs.
     */
    dci_PersonRecord: {
      identifier_type?: components['schemas']['dci_IdentifierType']
      /** @description Value of the identifier */
      identifier?: string
      name?: components['schemas']['dci_Name']
      /** @description Applicant preferred phone number as in [E.164](https://www.itu.int/rec/T-REC-E.164-201011-I/en) */
      phone_number?: string
      /** @description True if the End-User's phone number has been verified; otherwise false. */
      phone_number_verified?: string
      /** @description Applicant preferred e-mail address as in [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322) [addr-spec](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1) [specification](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1) */
      email?: string
      /** @description Email address was controlled by the End-User at the time the verification was performed. The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating. */
      email_verified?: boolean
      sex?: components['schemas']['dci_Sex']
      /** @description Represents Date and time of the applicant's birth as in [ISO 8601](https://www.iso.org/standard/40874.html) */
      birthdate?: string
      birthplace?: components['schemas']['openid_Address']
      deathdate?: components['schemas']['DateTime']
      deathplace?: components['schemas']['openid_Address']
      address?: components['schemas']['openid_Address']
      marital_status?: components['schemas']['dci_MaritalStatus']
      marriagedate?: components['schemas']['DateTime']
      divorcedate?: components['schemas']['DateTime']
      parent1_identifier?: {
        identifier_type?: components['schemas']['dci_IdentifierType']
        /** @description Value of the identifier */
        identifier?: string
      }
      parent2_identifier?: {
        identifier_type?: components['schemas']['dci_IdentifierType']
        /** @description Value of the identifier */
        identifier?: string
      }
    }
    /**
     * @description Predefined registry record to return in respone as object
     *
     * @enum {string}
     */
    dci_RecordType: 'person' | 'other'
    /**
     * @description Standardized codes/values representing diverse Sex categories.
     * Reference: [FHIR Administrative Gender](https://build.fhir.org/valueset-administrative-gender.html)
     * 1 : Male
     * 2 : Female
     * 3 : Others
     * 4 : Unknown
     *
     * @enum {string}
     */
    dci_Sex: 'male' | 'female' | 'other' | 'unknown'
    /**
     * @description Standardized codes/values represent vital events in an individual's life.
     * Reference: [Vital Events Statistics](https://mospi.gov.in/sites/default/files/publication_reports/vital_statistics_2010_0.pdf)<br>
     * 1 : Live Birth <br>
     * 2 : Death <br>
     * 3 : Fetal death <br>
     * 4 : Marriage <br>
     * 5 : Divorce <br>
     * 6 : Adoption <br>
     *
     * @enum {string}
     */
    dci_VitalEvents:
      | 'live_birth'
      | 'death'
      | 'fetal_death'
      | 'marriage'
      | 'divorce'
      | 'adoption'
    /** @description Refer [Plus Codes](https://github.com/google/open-location-code/wiki/Plus-codes-API) for more details */
    GooglePlusCode: {
      /** @example */
      global_code?: string
      geometry?: {
        bounds?: {
          northeast?: components['schemas']['LatLong']
          southwest?: components['schemas']['LatLong']
        }
        location?: components['schemas']['LatLong']
      }
    }
    /**
     * @description Standardized codes/values represent key events to [integrate](https://docs.mosip.io/1.2.0/integrations/mosip-opencrvs-integration#scope) with civil registries. <br><br>
     * **Sample flow to explain birth registration between MOSIP and CRVS systems:**
     * 1. Step 1: MOSIP subscribes to BIRTH_REGISTERED event with CRVS for RegistrationRecord
     * 2. Step 2: CRVS subscribes to BIRTH_REGISTERED event with MOSIP for MOSIPVerifiableCredential
     * 3. Step 3: CRVS notifies RegistrationRecord data to MOSIP
     * 4. Step 4: MOSIP notifies MOSIPVerifiableCredential data to CRVS <br>
     *
     * **Sample flow to explain data modification (push) flow from MOSIP to CRVS systems:**
     *   1. Step 1: CRVS subscribes to DATA_MODIFICATION event with MOSIP for MOSIPToken data
     *   2. Step 2: MOSIP notifies MOSIPToken data to CRVS<br>
     *
     * **Note:**
     * 1. Data modifiation (pull) flow can be accomodated with sync/search or existing mosip's eKyc auth api.
     * 2. Death, Death Reversal fllows same pattern as described in for birth registration.
     *
     * @enum {string}
     */
    mosip_EventType:
      | 'BIRTH_REGISTERED'
      | 'DEATH_REGISTERED'
      | 'DEATH_REVERSAL'
      | 'DATA_MODIFICATION'
    /** @description multi language value object */
    mosip_LangaugeValue: {
      /** @example eng */
      langugage?: string
      /** @example value */
      value?: string
    }
    mosip_LanguageValueList: components['schemas']['mosip_LangaugeValue'][]
    /** @description MOSIP Verifiable Credential for a [person](https://github.com/opencrvs/mosip-mediator/blob/master/samples/decrypted-sample-received-credentials.json) */
    mosip_MOSIPVerifiableCredential: {
      issuedTo?: string
      protectedAttributes?: string[]
      /** @description MOSIP Verifiable Credential for Proof of identity */
      credentialSubject?: {
        gender?: components['schemas']['mosip_LanguageValueList']
        city?: components['schemas']['mosip_LanguageValueList']
        /** @example 14022 */
        postalCode?: string
        /** @example Thirteen Mosip */
        fullName?: string
        /** @example 2022 */
        dateOfBirth?: string
        province?: components['schemas']['mosip_LanguageValueList']
        /** @example 9898989898 */
        phone?: string
        addressLine1?: components['schemas']['mosip_LanguageValueList']
        addressLine2?: components['schemas']['mosip_LanguageValueList']
        /** @example 2835824850916304 */
        id?: string
        /** @example 7346597054 */
        UIN?: string
        region?: components['schemas']['mosip_LanguageValueList']
        /** @example thirteen.mosip.123@mailinator.com */
        email?: string
      }
      /** @example http://mosip.io/credentials/e2039315-87b0-4012-942e-e0d7c879994b */
      id?: string
      type?: string[]
      consent?: string
      /** @example https://mosip.io/issuers/ */
      issuer?: string
    }
    /**
     * @description Predefined registry record to return in respone as object
     *
     * @enum {string}
     */
    mosip_RecordType: 'RegistrationRecord' | 'MOSIPVerifiableCredential'
    /** @description Birth Registration record to sync with MOSIP. [Reference](https://github.com/mosip/mosip-opencrvs/blob/develop/mediator/src/main/java/io/mosip/opencrvs/dto/SyncDto.java) */
    mosip_RegistrationRecord: {
      registrationId?: string
      packetId?: string
      additionalInfoReqId?: string
      name?: string
      email?: string
      phone?: string
      registrationType?: string
      packetHashValue?: string
      packetSize?: number
      supervisorStatus?: string
      supervisorComment?: string
      opentionalValues?: string[]
      langCode?: string
      createDateTime?: components['schemas']['DateTime']
      updateDateTime?: components['schemas']['DateTime']
      deletedDateTime?: components['schemas']['DateTime']
      isActive?: boolean
      isDeleted?: boolean
    }
    /** @description Deceased record obtainable from registries */
    nid_DeceasedRecord: {
      /** @description unique reference number mantained in the registry for recording death record or */
      reference_number?: string
      /** @description End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences. */
      name?: string
      /** @description End-User's gender. Values defined by this specification are female, male, transgender. */
      gender?: string
      /** @description Date of Birth in DDMMYYYY format */
      dob?: string
      /** @description Date of Death in DDMMYYYY format */
      dod?: string
      /** @description Date in DDMMYYYY format to record on which the death incident reported */
      reported_date?: string
      /** @description whether demo check has been undertaken or not */
      demo_check_status?: boolean
      /** @description Date in DDMMYYYY format to capture the Demo Check Date */
      demo_check_date?: string
      document?: components['schemas']['nid_Document']
    }
    /** @description Supporting document of the Resident,Reference document collected for registering the deceased information,Document encoded as Base64 string */
    nid_Document: {
      /** @description Name of the document */
      document_name?: string
      /** @description Bases 64 encoded document */
      document?: string
    }
    /** @description eKYC details of the resident ,ekyc Details undertaken by the Resident */
    nid_EKycDetails: {
      /** @description Date on which eKYC has been done. A null value indicates that eKYC has not been undertaken */
      ekyc_date?: string
    }
    /**
     * @description Predefined registry record to return in respone as object
     *
     * @enum {string}
     */
    nid_RecordType: 'resident_record' | 'deceased_record'
    /** @description Address of the Resident in English Language */
    nid_ResidentAddress: {
      /** @description Care of information */
      care_of?: string
      /** @description Building identity */
      building?: string
      /** @description Street details */
      street?: string
      /** @description Landmark details */
      landmark?: string
      /** @description Pincode */
      pincode?: string
      /** @description Post office name */
      'po-name'?: string
      /** @description Village Town City Code */
      vtc?: string
      /** @description Village/Town/City Name */
      'vtc-name'?: string
      /** @description Sub District Name */
      'sub-district-name'?: string
      /** @description District Name */
      'district-name'?: string
      /** @description State Name */
      state?: string
      /** @description Country Name */
      country?: string
    }
    /** @description Resident Local Address */
    nid_ResidentLocalAddress: {
      /** @description Care of information in local language */
      'local-careof'?: string
      /** @description Building information in local language */
      'local-building'?: string
      /** @description Street information in local language */
      'local-street'?: string
      /** @description Landmark information in local language */
      'local-landmark'?: string
      /** @description locality information in local language */
      'local-locality'?: string
      /** @description pincode */
      pincode?: string
      /** @description Post office name in local */
      'po-name-local'?: string
      /** @description vtc information in local language */
      'local-vtc'?: string
      /** @description Sub district information in local language */
      'local-subdistrict'?: string
      /** @description district information in local language */
      'local-district'?: string
      /** @description State information in local language */
      'local-state'?: string
      /** @description Country information in local language */
      'local-country'?: string
    }
    /** @description Resident Local Name */
    nid_ResidentLocalName: {
      language_code?: components['schemas']['LanguageCode']
      /** @description Local name of the Resident */
      local_name?: string
    }
    /** @description Resident Nationality Information,Nationality information of the Resident */
    nid_ResidentNationality: {
      /** @description Nationality information of the Resident */
      nationality?: string
      /** @description Passport number of the Resident */
      passport_number?: string
      /** @description Passport validity date in DDMMYYYY format */
      passport_valid_upto?: string
      /** @description Visa number of the Resident */
      visa_number?: string
      /** @description Visa validity details */
      visa_vald_upto?: string
      /** @description OCI card deatils */
      oci_number?: string
      /** @description OCI Validity date in DDMMYYYY format */
      oci_valid_upto?: string
    }
    /** @description Resident Photo,Image encoded as Base64 string */
    nid_ResidentPhoto: {
      /** @description Photo encoded as Base64 string */
      photo?: string
    }
    /** @description Resident Information */
    nid_ResidentRecord: {
      /** @description End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences. */
      name?: string
      /** @description End-User's gender. Values defined by this specification are female, male, transgender. */
      gender?: string
      /** @description Date of Birth in DDMMYYYY format */
      dob?: string
      /** @description Date of Birth Type i.e Declared, Approximate, Verified */
      dob_type?: string
      /** @description Phone number of the resident. If the number contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966 [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678. */
      phone?: string
      /** @description End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in Section 5.7. */
      email?: string
      address?: components['schemas']['nid_ResidentAddress']
      local_name?: components['schemas']['nid_ResidentLocalName']
      local_address?: components['schemas']['nid_ResidentLocalAddress']
      photo?: components['schemas']['nid_ResidentPhoto']
      nationality?: components['schemas']['nid_ResidentNationality']
      kyc_status?: components['schemas']['nid_EKycDetails']
      document?: components['schemas']['nid_Document']
    }
    /**
     * Address
     * @description Address info as per OpenID <a href="https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim">specs</a>
     */
    openid_Address: {
      /**
       * @description Full mailing address, formatted for display or use on a mailing label. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair ("\r\n") or as a single line feed character ("\n").
       * @example
       */
      address_line1?: string
      /**
       * @description Full street address component, which MAY include house number, street name, Post Office Box, and multi-line extended street address information. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair ("\r\n") or as a single line feed character ("\n").
       * @example
       */
      address_line_2?: string
      /**
       * @description City or locality component.
       * @example
       */
      locality?: string
      /** @description District or sub-regional code */
      sub_region_code?: string
      /**
       * @description State, province, prefecture, or region component.
       * @example
       */
      region_code?: string
      /**
       * @description Zip code or postal code component.
       * @example
       */
      postal_code?: string
      /**
       * @description Country part of an address represented using an ISO 3-letter code [ISO3166-3], e.g., "USA" or "JPN". 2-letter ISO codes [ISO3166-1] e.g. ,e.g. US, JP
       * @example
       */
      country_code?: string
      /** @description Refer [Plus Codes](https://github.com/google/open-location-code/wiki/Plus-codes-API) for more details */
      geo_location?:
        | components['schemas']['LatLong']
        | components['schemas']['GooglePlusCode']
    }
    /**
     * @description 1. Attributes of a person to create fetch records, create verifiable credentials or use in search criteria.
     * 2. Allowes Country/Registry specific implementation extensions using Attribute Name/Value pairs.
     * 3. Person info as per OpenID [Claims](https://openid.net/specs/openid-connect-core-1_0.html#Claims)
     * 4. Person additional info based on OpenID [name-additional-claims](https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html#name-additional-claims-about-end)
     */
    openid_PersonRecord: {
      /** @description Subject - Identifier for the End-User at the Issuer. */
      sub?: string
      /** @description End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences. */
      name?: string
      /** @description Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; all can be present, with the names being separated by space characters. */
      given_name?: string
      /** @description Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters. */
      family_name?: string
      /** @description Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used. */
      middle_name?: string
      /** @description Casual name of the End-User that may or may not be the same as the given_name. For instance, a nickname value of Mike might be returned alongside a given_name value of Michael. */
      nickname?: string
      /** @description Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique, as discussed in */
      preferred_username?: string
      /** @description URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User. */
      profile?: string
      /** @description URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User. */
      picture?: string
      /** @description URL of the End-User's Web page or blog. This Web page SHOULD contain information published by the End-User or an organization that the End-User is affiliated with. */
      website?: string
      /** @description End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in Section 5.7. */
      email?: string
      /** @description address was controlled by the End-User at the time the verification was performed. The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating. */
      email_verified?: boolean
      /** @description End-User's gender. Values defined by this specification are female and male. Other values MAY be used when neither of the defined values are applicable. */
      gender?: string
      /** @description YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just year can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates. */
      birthdate?: string
      /** @description End-User's place of birth. The value of this member is a JSON structure containing some or all of the following members */
      place_of_birth?: Record<string, never>
      /** @description YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just year can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates. */
      deathdate?: string
      /** @description End-User's place of birth. The value of this member is a JSON structure containing some or all of the following members */
      place_of_death?: Record<string, never>
      /** @description number contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966 [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678. */
      phone_number?: string
      /** @description True if the End-User's phone number has been verified; otherwise false. When this Claim Value is true, this means that the OP took affirmative steps to ensure that this phone number was controlled by the End-User at the time the verification was performed. The means by which a phone number is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating. When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be represented in RFC 3966 format. */
      phone_number_verified?: string
      address?: components['schemas']['openid_Address']
      /** @description String from zoneinfo [zoneinfo] time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles. */
      zoneinfo?: string
      /** @description Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, some implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as well. */
      locale?: string
      /** @description End-User's nationalities using ICAO 3-letter codes [ICAO-Doc9303], e.g., "USA" or "JPN". 2-letter ICAO codes MAY be used in some circumstances for compatibility reasons. */
      nationalities?: string[]
      /** @description Time the End-User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time */
      updated_at?: number
      /** @description End-User's family name(s) when they were born, or at least from the time they were a child. This term can be used by a person who changes the family name later in life for any reason. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters. */
      birth_family_name?: string
      /** @description End-User's given name(s) when they were born, or at least from the time they were a child. This term can be used by a person who changes the given name later in life for any reason. Note that in some cultures, people can have multiple given names; all can be present, with the names being separated by space characters. */
      birth_given_name?: string
      /** @description End-User's middle name(s) when they were born, or at least from the time they were a child. This term can be used by a person who changes the middle name later in life for any reason. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used. */
      birth_middle_name?: string
      /** @description End-User's salutation, e.g., "Mr." */
      salutation?: string
      /** @description End-User's title, e.g., "Dr." */
      title?: string
      /** @description End-User's mobile phone number formatted according to ITU-T recommendation [E.164], e.g., "1999550123" */
      msisdn?: string
      /** @description Stage name, religious name or any other type of alias/pseudonym with which a person is known in a specific context besides its legal name. This must be part of the applicable legislation and thus the trust framework (e.g., be an attribute on the identity card). */
      also_known_as?: string
      additional_attributes?: components['schemas']['AttributeNameValueList']
    }
    /**
     * @description 1. Person document detials as per OpenID [identity-assurance](https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html#name-evidence-element)
     * 2. JSON object representing the document used to perform the identity verification.
     */
    openid_PersonDocDetails: {
      /** @description String denoting the type of the document. The OP MAY use other than the predefined values in which case the RPs will either be unable to process the assertion, just store this value for audit purposes, or apply bespoken business logic to it. */
      type: string
      /** @description String Representing an identifier/number that uniquely identifies a document that was issued to the End-User. This is used on one document and will change if it is reissued, e.g., a passport number, certificate number, etc. Note, number can be used as an alias for 'document_number' for backward compatibility purposes but will be deprecated in future releases, implementers are recommended to use document_number. */
      document_number?: string
      /** @description String representing an identifier that is assigned to the End-User and is not limited to being used in one document, for example a national identification number, personal identity number, citizen number, social security number, driver number, account number, customer number, licensee number, etc. */
      personal_number?: string
      /** @description String representing an identifier/number that identifies the document irrespective of any personalization information (this usually only applies to physical artifacts and is present before personalization). */
      serial_number?: string
      /** @description The date the document was issued as ISO 8601 [ISO8601] YYYY-MM-DD format. */
      date_of_issuance?: string
      /** @description The date the document will expire as ISO 8601 [ISO8601] YYYY-MM-DD format. */
      date_of_expiry?: string
      /** @description JSON object containing information about the issuer of this document. This object consists of the following properties */
      issuer?: {
        /** @description Designation of the issuer of the document */
        name?: string
        address?: components['schemas']['openid_Address']
        /** @description String denoting the country or supranational organization that issued the document as ISO 3166/ICAO 3-letter codes [ICAO-Doc9303], e.g., "USA" or "JPN". 2-letter ICAO codes MAY be used in some circumstances for compatibility reasons. */
        country_code?: string
        /** @description String containing the name of the region(s)/state(s)/province(s)/municipality(ies) that issuer has jurisdiction over (if this information is not common knowledge or derivable from the address). */
        jurisdiction?: string
      }
    }
    /** @description Registry to notify a event to subscrbiers */
    NotifyEventRequest: {
      transaction_id: components['schemas']['TransactionId']
      notify_event: {
        reference_id: components['schemas']['ReferenceId']
        timestamp: components['schemas']['DateTime']
        /** @description Registry data being notified as an outcome of event subscription with registry */
        data: {
          /** @default 1.0.0 */
          version?: string
          reg_type: components['schemas']['RegistryType']
          reg_sub_type?: components['schemas']['RegistrySubType']
          reg_record_type: components['schemas']['RegistryRecordType']
          reg_records: components['schemas']['RegistryRecord']
        }
        locale?: components['schemas']['LanguageCode']
      }[]
    }
    /**
     * @description 1. Implementing systems can define schemas for each query types
     * 2. IdType Query is simple direct ID based lookup
     * 2. Pre Defined Named Query helps data provider to allow data access in a control manner and additional enforce RBAC policies
     * 3. PredicateQuery helps data consumer to access using defined context.
     * 4. Below are few examples that are possbile both in NamedQuery and PredicateQuery types: <br>
     *   - search or subscribe to update events; e.g any updates in postal_code 12345 between 1/jan/2020 and 31/dec/2020
     *   - search or subscribe to birth, death events; e.g any new birth in postal_code 12345 after 1/jan/2023
     *   - search all farmers with land area less than 2 acers in district code 504
     */
    RegistryQueries:
      | components['schemas']['NamedQuery']
      | components['schemas']['IdTypeQuery']
      | components['schemas']['PredicateQuery']
    /**
     * @description @context: "https://example.org/schema/RecordType" <br>
     * @type: "CRVSPerson" <br>
     * @container: "@set" <br>
     *
     * **Notes:**
     *   1. Record type values defined as per implementation context.
     *   2. Usually a list of **enum** values of all possible queryable identifiers.
     *
     * @example {
     *   "$ref": "components[\"schemas\"][\"dci_CRVSPerson\"]"
     * }
     */
    RegistryRecord: Record<string, never> | Array<Record<string, unknown>>
    /**
     * @description @context: "https://example.org/schema/RegistryRecordType" <br>
     * @type: "RegistryRecordType" <br>
     *
     * **Notes:**
     *   1. Registry record type values defined as per implementation context.
     *   2. Usually a list of **enum** values of all possible queryable result sets
     *   3. Referenced in search_request and notify events
     *   4. example: "ns:dci:RegistryRecordType:CRVSPerson"
     *
     * @example ns:dci:RegistryRecordType:CRVSPerson
     */
    RegistryRecordType: string
    /**
     * @description @context: "https://example.org/schema/RegistrySubType" <br>
     * @type: "VitalEvent" <br>
     *
     * **Notes:**
     *   1. Registry event type values defined as per implementation context.
     *   2. Usually a list of **enum** values of all possible queryable identifiers.
     *   3. example: "DCI:RegistrySubType:LiveBirth"
     *
     * @example DCI:RegistrySubType:LiveBirth
     */
    RegistrySubType: string
    /**
     * @description 1. Registry type defined as enum values by data provider
     * 2. This can also be a fully qualified namespace enum values
     * 3. example: "DCI:RegistryType:brith"
     *
     * @example DCI:RegistryType:brith
     */
    RegistryType: string
    /**
     * @description 1. Functional registry specific extension to search.
     * 2. Additional checks using conditioanl expressions is possible.
     * 3. Allows Country/Registry specific implementation extensions using key/value pairs.
     */
    SearchRequest: {
      transaction_id: components['schemas']['TransactionId']
      /** @description 1. Batch requests enabel multiple individual requests with respective consent/authorize codes */
      search_request: {
        reference_id: components['schemas']['ReferenceId']
        timestamp: components['schemas']['DateTime']
        search_criteria: {
          /** @default 1.0.0 */
          version?: string
          reg_type: components['schemas']['RegistryType']
          reg_sub_type?: components['schemas']['RegistrySubType']
          query_type: components['schemas']['QueryType']
          query: components['schemas']['RegistryQueries']
          sort?: components['schemas']['SearchSortList']
          pagination?: components['schemas']['PaginationRequest']
          consent?: components['schemas']['Consent']
          authorize?: components['schemas']['Authorize']
        }
        locale?: components['schemas']['LanguageCode']
      }[]
    }
    /** @description Response to search request. Multiple repsonses for each page can be pushed to the caller as an implementation! */
    SearchResponse: {
      transaction_id: components['schemas']['TransactionId']
      /**
       * @description 1. correlation_id acknowledged by end txn processing system (i.e receiver) to co-relate all related requests in the context of a business transaction.
       * 2. correlation_id uniqueness is ensured by txn processing system (i.e receiver)
       *
       * @example 9876543210
       */
      correlation_id: string
      search_response: {
        reference_id: components['schemas']['ReferenceId']
        timestamp: components['schemas']['DateTime']
        status: components['schemas']['RequestStatus']
        status_reason_code?: components['schemas']['SearchStatusReasonCode']
        /** @description Status reason code message. Helps actionanble messaging for systems/end users */
        status_reason_message?: string
        /** @description Search result record as an outcome of search/subscribe action */
        data?: {
          /** @default 1.0.0 */
          version?: string
          reg_type: components['schemas']['RegistryType']
          reg_sub_type?: components['schemas']['RegistrySubType']
          reg_record_type: components['schemas']['RegistryRecordType']
          reg_records: components['schemas']['RegistryRecord']
        }
        pagination?: components['schemas']['Pagination']
        locale?: components['schemas']['LanguageCode']
      }[]
    }
    /**
     * @description Identity verification request status reason codes
     * @enum {string}
     */
    SearchStatusReasonCode:
      | 'rjct.reference_id.invalid'
      | 'rjct.reference_id.duplicate'
      | 'rjct.timestamp.invalid'
      | 'rjct.search_criteria.invalid'
      | 'rjct.filter.invalid'
      | 'rjct.sort.invalid'
      | 'rjct.pagination.invalid'
      | 'rjct.search.too_many_records_found'
    /** @description Subscribe to a life event with crvs */
    SubscribeRequest: {
      transaction_id: components['schemas']['TransactionId']
      subscribe_request: {
        reference_id: components['schemas']['ReferenceId']
        timestamp: components['schemas']['DateTime']
        subscribe_criteria: {
          /** @default 1.0.0 */
          version?: string
          reg_type: components['schemas']['RegistryType']
          reg_sub_type?: components['schemas']['RegistrySubType']
          frequency?: components['schemas']['EventFrequency']
          filter_type?: components['schemas']['QueryType']
          filter: components['schemas']['RegistryQueries']
          notify_record_type: components['schemas']['RegistryRecordType']
          authorize?: components['schemas']['Authorize']
        }
        locale?: components['schemas']['LanguageCode']
      }[]
    }
    /** @description Response to subscribe request. */
    SubscribeResponse: {
      transaction_id: components['schemas']['TransactionId']
      correlation_id: components['schemas']['SearchResponse']['correlation_id']
      subscribe_response: {
        reference_id: components['schemas']['ReferenceId']
        timestamp: components['schemas']['DateTime']
        status: components['schemas']['RequestStatus']
        status_reason_code?: components['schemas']['SubscribeStatusReasonCode']
        /** @description Status reason code message. Helps actionanble messaging for systems/end users */
        status_reason_message?: string
        subscriptions?: components['schemas']['SubscriptionInfo'][]
        pagination?: components['schemas']['Pagination']
        locale?: components['schemas']['LanguageCode']
      }[]
    }
    /**
     * @description Identity verification request status reason codes
     * @enum {string}
     */
    SubscribeStatusReasonCode:
      | 'rjct.reference_id.invalid'
      | 'rjct.reference_id.duplicate'
      | 'rjct.timestamp.invalid'
      | 'rjct.notify_types.invalid'
      | 'rjct.notify_details.invalid'
      | 'rjct.person_id.invalid'
      | 'rjct.event.already_subscribed'
    /**
     * @description Unique code to identify the subscription request by the entity providing subscription service.
     * Helps to check status, unsubscribe etc.,
     */
    SubscriptionCode: string
    SubscriptionCodeList: unknown
    SubscriptionInfo: {
      /** @default 1.0.0 */
      version?: string
      code?: components['schemas']['SubscriptionCode']
      status?: components['schemas']['SubscriptionStatus']
      timestamp: components['schemas']['DateTime']
      reg_type?: components['schemas']['RegistryType']
      reg_sub_type?: components['schemas']['RegistrySubType']
      frequency?: components['schemas']['EventFrequency']
      filter_type?: components['schemas']['QueryType']
      filter?: components['schemas']['RegistryQueries']
      notify_record_type?: components['schemas']['RegistryRecordType']
      locale?: components['schemas']['LanguageCode']
    }
    /**
     * @description subscription status
     * @enum {string}
     */
    SubscriptionStatus: 'subscribe' | 'unsubscribe'
    /** @description Request to fetch txn status on various service requests */
    TxnStatusRequest: {
      transaction_id: components['schemas']['TransactionId']
      txnstatus_request: {
        reference_id: components['schemas']['ReferenceId']
        /**
         * @description txn type to fetch status
         * @enum {string}
         */
        txn_type: 'search' | 'subscribe' | 'unsubscribe'
        /** @enum {string} */
        attribute_type:
          | 'transaction_id'
          | 'reference_id_list'
          | 'correlation_id'
          | 'subscription_code_list'
        attribute_value:
          | components['schemas']['TransactionId']
          | components['schemas']['ReferenceIdList']
          | components['schemas']['SearchResponse']['correlation_id']
          | components['schemas']['SubscriptionCodeList']
        locale?: components['schemas']['LanguageCode']
      }
    }
    /** @description txn status info on various service requests */
    TxnStatusResponse: {
      transaction_id: components['schemas']['TransactionId']
      correlation_id: components['schemas']['SearchResponse']['correlation_id']
      /**
       * @example {
       *   "$ref": "components[\"schemas\"][\"SearchResponse\"]"
       * }
       */
      txnstatus_response: {
        /**
         * @description txn type to fetch status
         * @enum {string}
         */
        txn_type: 'on-search' | 'on-subscribe' | 'on-unsubscribe'
        txn_status:
          | components['schemas']['SearchResponse']
          | components['schemas']['SubscribeResponse']
          | components['schemas']['UnSubscribeResponse']
      }
    }
    /** @description Un-Subscribe to registred subscriptions */
    UnSubscribeRequest: {
      transaction_id: components['schemas']['TransactionId']
      timesstamp?: components['schemas']['DateTime']
      subscription_codes?: components['schemas']['SubscriptionCode'][]
    }
    /** @description Un-Subscribe to a life event with crvs */
    UnSubscribeResponse: {
      transaction_id: components['schemas']['TransactionId']
      correlation_id: components['schemas']['SearchResponse']['correlation_id']
      timesatmp?: components['schemas']['DateTime']
      status: components['schemas']['RequestStatus']
      status_reason_code?: components['schemas']['UnSubscribeStatusReasonCode']
      /** @description Status reason code message. Helps actionanble messaging for systems/end users */
      status_reason_message?: string
      subscription_status?: {
        code: components['schemas']['SubscriptionCode']
        status: components['schemas']['SubscriptionStatus']
      }[]
    }
    /**
     * @description Identity verification request status reason codes
     * @enum {string}
     */
    UnSubscribeStatusReasonCode:
      | 'rjct.reference_id.invalid'
      | 'rjct.reference_id.duplicate'
      | 'rjct.timestamp.invalid'
      | 'rjct.subscription_code.invalid'
      | 'rjct.requester.invalid'
      | 'rjct.event.already_unsubscribed'
    /**
     * @description 1. ACK: If the request is valid (for basic checks) and async callback (i.e webhook) will be invoked by reciever back to the sender.
     * 2. NACK: If the request is valid (for basic checks) and there is no futher updates from reciever back to the sender.
     * 3. ERR: If the reuqest is invalid and reciver can't process the request. error object holds error code, message.
     *
     * @enum {string}
     */
    Ack: 'ACK' | 'NACK' | 'ERR'
    /** @description Additional JSON property oject to hold custom user defined contextual data */
    AdditionalInfo: Record<string, never>
    /** @description Attribute name value object */
    AttributeNameValue: {
      /**
       * @description @context: "https://example.org/schema/Attribute" <br>
       * @type: "Attribute" <br>
       *
       * **Notes:**
       *   1. Attribute names defined as per implementation context.
       *   2. Usually a list of **enum** values of all possible attribute names.
       *   3. e.g: UIN, YOB, DOB, age, mobile, area-code, pin-code, etc.,
       *
       * @example YOB
       */
      name: string
      value: components['schemas']['AttributeValue']
    }
    /** @description List of attribute Name/Value */
    AttributeNameValueList: components['schemas']['AttributeNameValue'][]
    /** @example 1980 */
    AttributeValue: string | number | boolean | Record<string, never>
    /**
     * @description @context: "https://example.org/schema/Authorize" <br>
     * @type: "Authorize"
     *
     * @example {
     *   "@context": "https://example.org/schema/Authorize",
     *   "@type": "Authorize",
     *   "ts": {
     *     "$ref": "components[\"schemas\"][\"DateTime\"]"
     *   },
     *   "purpose": {
     *     "text": {
     *       "type": "string"
     *     },
     *     "code": {
     *       "type": "string",
     *       "description": "From a fixed set, documented at refUri"
     *     },
     *     "refUri": {
     *       "type": "string",
     *       "format": "uri",
     *       "description": "Uri to provide more info on authorize codes"
     *     }
     *   }
     * }
     */
    Authorize: Record<string, never>
    /**
     * @description @context: "https://example.org/schema/Consent" <br>
     * @type: "Consent"
     *
     * @example {
     *   "@context": "https://example.org/schema/Consent",
     *   "@type": "Consent",
     *   "ts": {
     *     "$ref": "components[\"schemas\"][\"DateTime\"]"
     *   },
     *   "purpose": {
     *     "text": {
     *       "type": "string"
     *     },
     *     "code": {
     *       "type": "string",
     *       "description": "From a fixed set, documented at refUri"
     *     },
     *     "refUri": {
     *       "type": "string",
     *       "format": "uri",
     *       "description": "Uri to provide more info on consent codes"
     *     }
     *   }
     * }
     */
    Consent: Record<string, never>
    /**
     * Format: date-time
     * @description 1. All dates and timestamps are represented in [ISO 8601](https://www.iso.org/standard/40874.html) format including timezone - e.g 2022-12-04T17:20:07-04:00.
     *
     * @example
     */
    DateTime: string
    /** @description Encrypted payload */
    EncryptedMessage: {
      header: {
        /** @description The JWE algorithm used for encryption */
        alg: string
        /** @description The encryption algorithm used for encrypting the plaintext */
        enc: string
        /** @description The key identifier for the encryption key */
        kid: string
      }
      /** @description This is the result of encrypting the plaintext using the CEK and the IV. It's Base64Url-encoded. */
      ciphertext: string
      /** @description The base64-url encoded encrypted key */
      encrypted_key: string
      /** @description This is a Base64Url-encoded value that provides evidence of the integrity and authenticity of the ciphertext, Initialization Vector, and Additional Authenticated Data */
      tag: string
      /** @description This is a Base64Url-encoded random bit string to be used as the Initialization Vector (IV) when encrypting the plaintext to produce the ciphertext. The size of the IV depends on the encryption algorithm used. */
      iv: string
    }
    /**
     * @description Commumication layer Asyn errors that are returned as part of message acknowledgement.
     * 1. Messages that are not parsable or message integrity check fails.
     * 2. This object may be used across all transport layer protocols (https, sftp, messaging, etc,) to ack the receipt of a message.
     * 3. Business context and related validation is NOT in scope of this error object.
     */
    Error: {
      /**
       * @description Standard error code
       * @enum {string}
       */
      code?:
        | 'err.request.bad'
        | 'err.request.unauthorized'
        | 'err.request.forbidden'
        | 'err.request.not_found'
        | 'err.request.timeout'
        | 'err.version.not_supported'
        | 'err.request.too_many_requests'
        | 'err.sender_id.invalid'
        | 'err.sender_uri.invalid'
        | 'err.receiver_id.invalid'
        | 'err.signature.missing'
        | 'err.signature.invalid'
        | 'err.encryption.invalid'
        | 'err.service.unavailable'
      /** @description message to describe above error code */
      message?: string
    }
    /**
     * @description 1. Frequency at which subscribed services should be notified.
     * 2. start_time, end_time represent data range where the notification frequency is applicable
     */
    EventFrequency: {
      start_time: components['schemas']['DateTime']
      end_time: components['schemas']['DateTime']
      /**
       * @description Frequency at which notification is required. This will be in the form of cron expression.
       * Example - "0 0 0 5,15 * ? *"
       * which says At 00:00:00am, on the 5th and 15th day, every month
       */
      frequency: string
    }
    /**
     * @description Condition in an expression
     * @example and
     * @enum {string}
     */
    ExpCondition: 'and' | 'or' | 'not'
    /**
     * @description Operator in an expression
     * @example eq
     * @enum {string}
     */
    ExpOperator: 'gt' | 'lt' | 'eq' | 'ge' | 'le' | 'in'
    /** @description File info. Used in file upload feature using HTTPS */
    FileInfo: {
      /** @description G2P Connect specific actions. Usually verb from the URI should go here to help store and fwd kind of processing requirements. */
      action: string
      /**
       * Format: binary
       * @description Disbursement instruction file representing Disburse or OnDisburse end point elements i.e signature/header/message entities as a file record
       */
      fileName: string
      /**
       * @description File content format. e.g json, csv, etc.,
       * @default json
       * @example csv
       */
      fileFormat?: string
    }
    /**
     * @description @context: "https://example.org/schema/IdType" <br>
     * @type: "IdType" <br>
     *
     * **Notes:**
     *   1. Identifier type values defined as per implementation context.
     *   2. Usually a list of **enum** values of all possible queryable identifiers.
     *   3. e.g: UIN, MOBILE, BRN, MRN, DRN, etc.,
     *
     * @example UIN
     */
    IdentifierType: string
    /** @description Identifier type and value object */
    IdTypeQuery: {
      /**
       * @description @context: "https://example.org/schema/IdType" <br>
       * @type: "IdType" <br>
       *
       * **Notes:**
       *   1. Identifier type values defined as per implementation context.
       *   2. Usually a list of **enum** values of all possible queryable identifiers.
       *   3. e.g: UIN, MOBILE, BRN, MRN, DRN, etc.,
       *
       * @example UIN
       */
      type?: string
      /** @example 12314567890 */
      value?: components['schemas']['AttributeValue']
    }
    /**
     * @description indicates language code. G2P Connect supports country codes as per ISO 639.3 standard
     * @example en
     */
    LanguageCode: string
    LatLong: {
      /** @example 11°24'12.2"N */
      latitude?: string
      /** @example 88°50'26.5"E */
      longitude?: string
    }
    /**
     * @description @context: "https://example.org/schema/Meta" <br>
     * @type: "@context" <br>
     *
     * **Notes:**
     *   1. Additional meta info defined as per implementation context.
     *   2. Usually unencrypted list of name/value, tags, etc., to provide additional info to intermediary entities.
     *   3. The information SHOULD be privacy preserving
     */
    Meta: Record<string, never>
    /** @description Message header */
    'MsgCallbackHeader_V1.0.0': {
      /**
       * @description Messaing protocol specification version being used
       * @default 1.0.0
       */
      version?: string
      /**
       * @description 1. Unique message id to communicate between sender and receiver systems to realiable deliver the message over any transport layer i.e https, pub/sub, sftp etc.,
       * 2. The scope of message_id end with successful ack of the message by the receiver.
       * 3. To realy the message between hops, underlying relying parties may consider to store and forward the message with integirty, ie Signature intact.
       *
       * @example 789
       */
      message_id: string
      message_ts: components['schemas']['DateTime']
      /** @description G2P Connect specific action. Usually verb from the URI should go here to help store and fwd kind of processing requirements. */
      action: string
      status: components['schemas']['RequestStatus']
      status_reason_code?: components['schemas']['MsgHeaderStatusReasonCode']
      /** @description Status reascon code message, if any, Helps actionanble messaging for system/end users */
      status_reason_message?: string
      /**
       * @description Total no of requests present in the message request
       * @example 21800
       */
      total_count?: number
      /**
       * @description No of requests in complteed state. Complete includes success and error requests due to funcational errors
       * @example 50
       */
      completed_count?: number
      /**
       * @description 1. sender_id registered with the receiving system or gateway.
       * 2. Used for authorization, encryption, digital sign verfication, etc.,
       *
       * @example civilregistry.example.org
       */
      sender_id?: string
      /**
       * @description receiver id registered with the calling system. Used for authorization, encryption, digital sign verfication, etc., functions.
       * @example registry.example.org
       */
      receiver_id?: string
      /**
       * @description Is message encrypted?
       * @default false
       */
      is_msg_encrypted?: boolean
      meta?: components['schemas']['Meta']
    }
    /** @description Message header */
    'MsgHeader_V1.0.0': {
      /**
       * @description Messaing protocol specification version being used
       * @default 1.0.0
       */
      version?: string
      /**
       * @description 1. Unique message id to communicate between sender and receiver systems to realiable deliver the message over any transport layer i.e https, pub/sub, sftp etc.,
       * 2. The scope of message_id end with successful ack of the message by the receiver.
       * 3. To realy the message between hops, underlying relying parties may consider to store and forward the message with integirty, ie Signature intact.
       *
       * @example 123
       */
      message_id: string
      message_ts: components['schemas']['DateTime']
      /** @description G2P Connect specific action. Usually verb from the URI. Helps in sync, async, store/fwd processing. Helps identity payload type in message property. */
      action: string
      /**
       * @description 1. sender_id registered with the receiving system or gateway.
       * 2. Used for authorization, encryption, digital sign verfication, etc.,
       *
       * @example spp.example.org
       */
      sender_id: string
      /**
       * Format: uri
       * @description 1. sender url to accept callbacks. Applicable only for async communications and if response ack_status is ACK.
       * 2. Default uri is assumed to be configred on the gateway as part of sender/receiver onboarding.
       * 3. For SFTP based communications, this shall be set to server/folder details.
       *
       * @example https://spp.example.org/{namespace}/callback/on-search
       */
      sender_uri?: string
      /**
       * @description receiver id registered with the calling system. Used for authorization, encryption, digital sign verfication, etc., functions.
       * @example pymts.example.org
       */
      receiver_id?: string
      /**
       * @description Total no of requests present in the message request
       * @example 21800
       */
      total_count: number
      /**
       * @description Is message encrypted?
       * @default false
       */
      is_msg_encrypted?: boolean
      meta?: components['schemas']['Meta']
    }
    /**
     * @description Message header related common status reason codes
     * @enum {string}
     */
    MsgHeaderStatusReasonCode:
      | 'rjct.version.invalid'
      | 'rjct.message_id.duplicate'
      | 'rjct.message_ts.invalid'
      | 'rjct.action.invalid'
      | 'rjct.action.not_supported'
      | 'rjct.total_count.invalid'
      | 'rjct.total_count.limit_exceeded'
      | 'rjct.errors.too_many'
    /**
     * @description Signature of {header}+{message} body verified using sender's signing public key
     * @example Signature:  namespace="g2p", kidId="{sender_id}|{unique_key_id}|{algorithm}", algorithm="ed25519", created="1606970629", expires="1607030629", headers="(created) (expires) digest", signature="Base64(signing content)
     */
    MsgSignature: string
    /** @description Identifier type and value object */
    NamedQuery: {
      /**
       * @description 1. Predefined NamedQuery that assumes all conditions as a template
       * 2. The required parameters defined in the template are passed in queryParams
       * 3. List of named queries are documented and made available by data providers to all authorised data consumers
       * 4. Named Queries can also be uniquely identfied by data providers to implement RBAC policies
       * 5. Return result record set is defined as part of Named Queries by data providers
       *
       * @example DCI:NamedQuery:getBirthByBRNandAreaCode
       */
      query_name?: string
      /**
       * @description @context: "https://example.org/schema/QueryParam" <br>
       * @type: "QueryParam" <br>
       *
       * @example {
       *   "BRN": "1111",
       *   "area_code": "123"
       * }
       */
      query_params?: Record<string, never>
    }
    /** @description Pagination definition, count starts with 1 */
    Pagination: {
      /**
       * Format: int32
       * @example 2000
       */
      page_size: number
      /**
       * Format: int32
       * @example 5
       */
      page_number: number
      /**
       * Format: int32
       * @example 24250
       */
      total_count: number
    }
    /** @description Pagination definition, count starts with 1 */
    PaginationRequest: {
      /**
       * Format: int32
       * @example 2000
       */
      page_size: number
      /**
       * Format: int32
       * @default 1
       * @example 5
       */
      page_number?: number
    }
    /** @description Expression */
    Predicate: {
      /**
       * @description @context: "https://example.org/schema/QueryAttributes" <br>
       * @type: "QueryAttributes" <br>
       *
       * **Notes:**
       *   1. Query attribute names defined as per implementation context.
       *   2. Usually a list of **enum** values of all possible queryable attribute names.
       *   3. e.g: UIN, YOB, DOB, age, mobile, area-code, pin-code, etc.,
       *
       * @example YOB
       */
      attribute_name: string
      operator: components['schemas']['ExpOperator']
      attribute_value: components['schemas']['AttributeValue']
    }
    /** @description list of attributes with matching conditions */
    PredicateList: components['schemas']['Predicate'][]
    PredicateWithCondition: {
      /**
       * @description Sequence number to help define precedence for evaluating a list of expression Predicates
       * @example 1
       */
      seq_num?: number
      expression1: components['schemas']['Predicate']
      condition?: components['schemas']['Predicate']
      expression2?: components['schemas']['Predicate']
    }
    PredicateQuery: components['schemas']['PredicateWithCondition'][]
    /**
     * @description 1. Query format allow multiple ways to search registry
     * 2. Templatized query expressions with placeholder for conditional values
     *
     * @example namedQuery
     * @enum {string}
     */
    QueryType: 'namedQuery' | 'idtype' | 'predicate'
    /**
     * @description Unique reference_id set by txn initiating system for each request in a batch
     * @example 12345678901234567890
     */
    ReferenceId: string
    ReferenceIdList: components['schemas']['ReferenceId'][]
    /**
     * @description Request (e.g disburse, link, unlink, resolve, issue, search, verify, etc.,) status: <br> 1. rcvd: Received; Request received <br> 2. pdng: Pending; Request initiated <br> 3. succ: Success; Request successful <br> 4. rjct: Rejected; Request rejected
     * @enum {string}
     */
    RequestStatus: 'rcvd' | 'pdng' | 'succ' | 'rjct'
    /** @description Sorting definition */
    SearchSort: {
      /**
       * @description @context: "https://example.org/schema/Attribute" <br>
       * @type: "Attribute" <br>
       *
       * **Notes:**
       *   1. Attribute names defined as per implementation context.
       *   2. Usually a list of **enum** values of all possible attribute names.
       *   3. e.g: UIN, YOB, DOB, age, mobile, area-code, pin-code, etc.,
       *
       * @example YOB
       */
      attribute_name?: string
      /** @enum {string} */
      sort_order?: 'asc' | 'desc'
    }
    SearchSortList: components['schemas']['SearchSort'][]
    /**
     * @description 1. transaction_id set by txn initiating system (i.e sender) to co-relate all related requests in the context of a business transaction.
     * 2. transaction_id should be samme across processing systems/service end points.
     * 2. transaction_id uniqueness is ensured by txn initiating system (i.e sender)
     *
     * @example 123456789
     */
    TransactionId: string
  }
  responses: {
    /** @description HTTP layer error details */
    HttpErrorResponse: {
      content: {
        'application/json': {
          errors?: unknown
        }
      }
    }
    /** @description Acknowledgement of message received after successful validation of message and signature */
    Response: {
      content: {
        'application/json': {
          message?: {
            ack_status: components['schemas']['Ack']
            timestamp: components['schemas']['DateTime']
            error?: components['schemas']['Error']
            correlation_id: components['schemas']['SearchResponse']['correlation_id']
          }
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /**
   * /registry/search
   * @description Search person(s) in registry using identifier or custome attributes
   */
  post_reg_search: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'search'
          }
          /** @description The search data using which registry search to be performed */
          message:
            | components['schemas']['SearchRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'search'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/on-search
   * @description Search results through callback
   */
  'post_reg_on-search': {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'on-search'
          }
          message?:
            | components['schemas']['SearchResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'on-search'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/subscribe
   * @description Subscribe to a life event with registry
   */
  post_reg_subscribe: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'subscribe'
          }
          /** @description Subscription request which contaion query with frequency and other info on which notification to be sent by registry to subscriber */
          message:
            | components['schemas']['SubscribeRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'subscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/on-subscribe
   * @description Subscribe results through callback
   */
  'post_reg_on-subscribe': {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'on-subscribe'
          }
          /** @description Subscription information */
          message:
            | components['schemas']['SubscribeResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'on-subscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/notify
   * @description Registry to notify a life event to subscrbiers
   */
  post_reg_notify: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'notify'
          }
          message?:
            | components['schemas']['NotifyEventRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'notify'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['HttpErrorResponse']
    }
  }
  /**
   * /registry/unsubscribe
   * @description Unsubscribe existing subscription(s) by subscription_code
   */
  post_reg_unsubscribe: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'unsubscribe'
          }
          /** @description The unsubscribe request that contain subscription ids which to be removed from subscription list */
          message:
            | components['schemas']['UnSubscribeRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'unsubscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/on-unsubscribe
   * @description Unsubscribe response as a callback
   */
  'post_reg_on-unsubscribe': {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'on-unsubscribe'
          }
          message:
            | components['schemas']['UnSubscribeResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'on-unsubscribe'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/txn/status
   * @description Perform async status check of previous civil registry transanctions using transaction_id and/or reference_id(s)
   */
  post_reg_txnstatus: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'txn-status'
          }
          message:
            | components['schemas']['TxnStatusRequest']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'txn-status'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/txn/on-status
   * @description Response to async status check of previous civil registrt transanctions using callback
   */
  'post_reg_on-txnstatus': {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'txn-on-status'
          }
          message?:
            | components['schemas']['TxnStatusResponse']
            | components['schemas']['EncryptedMessage']
        }
        'multipart/form-data': components['schemas']['FileInfo'] & {
          /** @enum {unknown} */
          action?: 'txn-on-status'
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      default: components['responses']['Response']
    }
  }
  /**
   * /registry/sync/search
   * @description Search person(s) in registry using identifier or custome attributes
   */
  post_reg_sync_search: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'search'
          }
          /** @description The search data using which registry search to be performed */
          message:
            | components['schemas']['SearchRequest']
            | components['schemas']['EncryptedMessage']
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      /** @description Registry search response */
      default: {
        content: {
          'application/json': {
            signature?: components['schemas']['MsgSignature']
            header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
              /** @enum {unknown} */
              action?: 'on-search'
            }
            message?:
              | components['schemas']['SearchResponse']
              | components['schemas']['EncryptedMessage']
          }
        }
      }
    }
  }
  /**
   * /registry/sync/txn/status
   * @description Sync status check of registry Async APIs
   */
  post_reg_sync_txnstatus: {
    requestBody: {
      content: {
        'application/json': {
          signature?: components['schemas']['MsgSignature']
          header: components['schemas']['MsgHeader_V1.0.0'] & {
            /** @enum {unknown} */
            action?: 'txn-status'
          }
          message:
            | components['schemas']['TxnStatusRequest']
            | components['schemas']['EncryptedMessage']
        }
      }
    }
    responses: {
      401: components['responses']['HttpErrorResponse']
      403: components['responses']['HttpErrorResponse']
      500: components['responses']['HttpErrorResponse']
      /** @description Transaction status check response */
      default: {
        content: {
          'application/json': {
            signature?: components['schemas']['MsgSignature']
            header: components['schemas']['MsgCallbackHeader_V1.0.0'] & {
              /** @enum {unknown} */
              action?: 'txn-on-status'
            }
            message?:
              | components['schemas']['TxnStatusResponse']
              | components['schemas']['EncryptedMessage']
          }
        }
      }
    }
  }
}
