name: GraphQL version compability with opencrvs-core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    strategy:
      matrix:
        supported-core-version: [develop, release-v1.5.0, release-v1.4.2]
    uses: naftis/opencrvs-actions/.github/workflows/validate-graphql-queries.yml@91cf8b75a8761ac0bca763626c8820d18f2d752f
    with:
      schema: https://raw.githubusercontent.com/opencrvs/opencrvs-core/refs/heads/${{ matrix.supported-core-version }}/packages/gateway/src/graphql/schema.graphql
