name: Run tests

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
